cargo-features = ["strip"]

[workspace]
members = [
    "src-wasm/*",
]
resolver = "2"

[profile]
[profile.release]
lto = true
codegen-units = 1
opt-level = 3
strip = "symbols"
panic = 'abort'

[profile.dev]
opt-level = 1

[profile.dev.package.'*']
codegen-units = 1
opt-level = 3
