[package]
name = "app-core"
version = "0.1.0"
edition = "2018"

[dependencies.bevy]
version = "0.5"
# path = "../../bevy"
git = "https://github.com/bevyengine/bevy.git"
rev = "081350916c39fc1c7c9d659ccb6d86413832b465"
# branch = "main"
default-features = false
