name = "shrm-api"
main = "dist/index.mjs"
usage_model = 'bundled'
compatibility_flags = []
workers_dev = true
compatibility_date = "2022-10-13"

kv_namespaces = [
]

[vars]

[durable_objects]
bindings = [
  { name = "USER", class_name = "User" },
  { name = "COURSES", class_name = "Courses" },
  { name = "SESSIONS", class_name = "Session" },
]

[[migrations]]
tag = "v1"
new_classes = ["User", "Courses"]

[[migrations]]
tag = "v2"
new_classes = ["Session"]

[build]
command = "yarn install && yarn build"
