mod colors;
mod z_index;

pub use colors::*;
pub use z_index::*;

pub const MOVE_IMPULSE_MULTIPLIER_GROUND: f32 = 0.04 * GROUND_FRICTION_MULTIPLIER * RAPIER_GRAVITY;
pub const MOVE_IMPULSE_MULTIPLIER_GROUND_RUN: f32 =
    0.047 * GROUND_FRICTION_MULTIPLIER * RAPIER_GRAVITY;
pub const MOVE_IMPULSE_MULTIPLIER_AIR: f32 = 35.;
pub const MOVE_IMPULSE_MULTIPLIER_AIR_RUN: f32 = 40.;

pub const LINVEL_CAP_WALK: f32 = 170.;
pub const LINVEL_CAP_RUN: f32 = 300.;
pub const LINVEL_CAP_STOOP: f32 = 80.;
pub const LINVEL_BUILD: f32 = 250.;

pub const PLAYER_COLLIDER_BORDER_RADIUS: f32 = 0.4;
pub const COLLIDER_MAX_TOI: f32 = 1. / 60.;
pub const COLLIDER_TOI_THRESHOLD: f32 = 12. / 60.;

pub const RUN_THRESHOLD: f32 = LINVEL_CAP_RUN * 0.9;
pub const HIGH_JUMP_WALK_THRESHOLD: f32 = 7.;

pub const JUMP_FORCE: f32 = 300.;
pub const HIGH_JUMP_TICK: u8 = 15;
pub const HIGH_JUMP_TICK_WALK: u8 = 22;

pub const RAPIER_SCALE: f32 = 10.;
pub const RAPIER_GRAVITY: f32 = 120.;

const GROUND_FRICTION_MULTIPLIER: f32 = 15.;
pub const GROUND_FRICTION: f32 = GROUND_FRICTION_MULTIPLIER * 70. / RAPIER_GRAVITY;
pub const GROUND_FRICTION_MIN_VEL: f32 = 1.5;
pub const GROUND_FRICTION_STATIC_MULTIPLIER: f32 = 2.5 / 60.;
pub const GROUND_FRICTION_KINETIC_MULTIPLIER: f32 = 0.3 / 60.;
pub const GROUND_PADDING: f32 = 1.1;

pub const TILE_SIZE: f32 = 2.;
pub const TILE_COLLIDER_SUB: f32 = 0.55;
pub const GRID_MARGIN: f32 = 0.1;
pub const GRID_SIZE: f32 = TILE_SIZE * 2. - (2. * TILE_COLLIDER_SUB) + (2. * GRID_MARGIN);
pub const GROUND_MARGIN_MULTIPLIER: f32 = 2.;
pub const GRID_MULTIPLIER: f32 = 4.8;
pub const TILE_GRID_SIZE: f32 = (TILE_SIZE - TILE_COLLIDER_SUB + GRID_MARGIN) * GRID_MULTIPLIER;
pub const GRID_COLLISION_PROJECTION_MULTIPLIER: f32 = 2.15;

pub const CAMERA_SCALE: f32 = 0.7;
pub const CAMERA_MIN_X: f32 = 1240. * 0.7 / 2.;
pub const CAMERA_MIN_Y: f32 = 680. * 0.7 / 2.;

pub const MAX_COURSE_X: i32 = 150;
pub const MAX_COURSE_Y: i32 = 24;
pub const MAX_COURSE_GOAL_OFFSET_X: i32 = 16;
pub const MIN_GOAL_POS_X: i32 = 32;
pub const MAX_GOAL_POS_X: i32 = MAX_COURSE_X - MAX_COURSE_GOAL_OFFSET_X;
