use bevy_rapier::na::Vector2;

pub const MOVE_IMPULSE_MULTIPLIER_GROUND: f32 = 0.6 * GROUND_FRICTION_MULTIPLIER * RAPIER_GRAVITY;
pub const MOVE_IMPULSE_MULTIPLIER_AIR: f32 = 30000.;

pub const LINVEL_CAP_GROUND: (f32, f32) = (17.5, 100.);
pub const LINVEL_CAP_AIR: (f32, f32) = (100., JUMP_FORCE);

pub const JUMP_FORCE: f32 = 37.;
pub const HIGH_JUMP_TICK: u8 = 15;

pub const RAPIER_SCALE: f32 = 10.;
pub const RAPIER_GRAVITY: f32 = 200.;
pub const RAPIER_GRAVITY_VECTOR: Vector2<f32> = Vector2::new(0., -RAPIER_GRAVITY);

const GROUND_FRICTION_MULTIPLIER: f32 = 35.;
pub const GROUND_FRICTION: f32 = GROUND_FRICTION_MULTIPLIER / RAPIER_GRAVITY;
