[package]
name = "app-debug"
version = "0.1.0"
edition = "2018"

[dependencies]
js-sys = "0.3"
rapier = { package = "rapier2d", version = "0.10" }
wasm-bindgen = "0.2"

[dependencies.bevy]
version = "0.5"
git = "https://github.com/bevyengine/bevy.git"
branch = "main"
default-features = false
