name: Publish

on:
  push:
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install Node dependencies
        run: yarn install

      - uses: actions-rs/toolchain@v1
        name: Install Toolchain
        with:
          profile: minimal
          toolchain: nightly-2022-06-02
          override: true

      - name: Install Rust WebAssembly
        run: rustup target add wasm32-unknown-unknown

      - name: Install wasm bindgen
        run: cargo install --version 0.2.80 wasm-bindgen-cli

      - name: Install wasm-opt
        run: |
          curl -L https://github.com/WebAssembly/binaryen/releases/download/version_108/binaryen-version_108-x86_64-linux.tar.gz --output binaryen.tar.gz
          tar -zxvf binaryen.tar.gz binaryen-version_108/bin/wasm-opt
          mv binaryen-version_108/bin/wasm-opt wasm-opt

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build site
        run: |
          yarn build
          ./wasm-opt -O4 dist/app_bg.wasm -o dist/app_bg.wasm

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
