name: Test

on: [push]

env:
  WASM_BINDGEN_VERSION: 0.2.80

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install Node dependencies
        run: yarn install

      - uses: actions-rs/toolchain@v1
        name: Install Toolchain
        with:
          profile: minimal
          toolchain: nightly-2022-06-02
          override: true
          components: rustfmt, clippy

      - name: Install Rust WebAssembly
        run: rustup target add wasm32-unknown-unknown

      - name: Install wasm bindgen
        run: |
          curl -L https://github.com/rustwasm/wasm-bindgen/releases/download/${{ env.WASM_BINDGEN_VERSION }}/wasm-bindgen-${{ env.WASM_BINDGEN_VERSION }}-x86_64-unknown-linux-musl.tar.gz --output wasm-bindgen.tar.gz
          tar -zxvf wasm-bindgen.tar.gz wasm-bindgen-${{ env.WASM_BINDGEN_VERSION }}-x86_64-unknown-linux-musl/wasm-bindgen
          mv wasm-bindgen-${{ env.WASM_BINDGEN_VERSION }}-x86_64-unknown-linux-musl/wasm-bindgen /home/runner/.local/bin/wasm-bindgen

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions-rs/cargo@v1
        name: Fmt
        with:
          command: fmt
          args: --all -- --check

      - uses: actions-rs/cargo@v1
        name: Clippy
        with:
          command: clippy
          args: -- -D warnings

      # TODO
      # - uses: actions-rs/cargo@v1
      #   name: Test
      #   with:
      #     command: test
