name: Publish

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install Node dependencies
        run: yarn install

      - uses: actions-rs/toolchain@v1
        name: Install Toolchain
        with:
          profile: minimal
          toolchain: nightly-2022-05-27
          override: true

      - name: Install Rust WebAssembly
        run: rustup target add wasm32-unknown-unknown

      - name: Install wasm bindgen
        run: cargo install --version 0.2.80 wasm-bindgen-cli

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions-rs/cargo@v1
        name: Fmt
        with:
          command: fmt
          args: --all -- --check

      - uses: actions-rs/cargo@v1
        name: Clippy
        with:
          command: clippy
          args: -- -D warnings

      # TODO
      # - uses: actions-rs/cargo@v1
      #   name: Test
      #   with:
      #     command: test
